SELECT *
FROM fastfood
ORDER BY id;

--전국 시,군,구 숫자 --결과 205개
SELECT SIDO||SIGUNGU city
FROM fastfood
GROUP BY SIDO||SIGUNGU
ORDER BY city;

--버거킹 숫자
SELECT *
FROM fastfood
WHERE gb='버거킹'
ORDER BY id;

SELECT SIDO||SIGUNGU AS city, COUNT(SIDO||SIGUNGU)
FROM fastfood
WHERE gb = '버거킹'
GROUP BY SIDO||SIGUNGU
ORDER BY SIDO||SIGUNGU;

SELECT SIDO||SIGUNGU AS city, COUNT(SIDO||SIGUNGU)
FROM fastfood
WHERE gb = '맥도날드'
GROUP BY SIDO||SIGUNGU
ORDER BY SIDO||SIGUNGU;

SELECT SIDO||SIGUNGU AS city, COUNT(SIDO||SIGUNGU)
FROM fastfood
WHERE gb = 'KFC'
GROUP BY SIDO||SIGUNGU
ORDER BY SIDO||SIGUNGU;

SELECT SIDO||SIGUNGU AS city, COUNT(SIDO||SIGUNGU)
FROM fastfood
WHERE gb = '롯데리아'
GROUP BY SIDO||SIGUNGU
ORDER BY SIDO||SIGUNGU;

SELECT *
FROM fastfood;

SELECT main.SIDO, main.SIGUNGU, round(main.cnt/sub.cnt, 2) point
FROM (SELECT SIDO, SIGUNGU, COUNT(SIGUNGU) cnt
FROM fastfood
WHERE gb IN ('버거킹','맥도날드','KFC')
GROUP BY SIDO, SIGUNGU) main JOIN
(SELECT SIDO, SIGUNGU, COUNT(SIGUNGU) cnt
FROM fastfood
WHERE gb IN ('롯데리아')
GROUP BY SIDO, SIGUNGU) sub
ON (main.SIDO||main.SIGUNGU = sub.SIDO||sub.SIGUNGU)
ORDER BY main.SIDO, main.SIGUNGU;